### PR TITLE
Adds tests from php.net for Array methods not yet implemented

### PR DESCRIPTION
**Pull request by bouiboui**
Adds tests for soon-to-be implemented Array functions discussed in Issue #4.
The tests are examples from php.net converted to tests.

Functions without examples on php.net were given placeholders (commented).

### CODE REVIEW

**Comment by rossriley** [comment]
Nice work. I'll get merging.

**Comment by bouiboui** [comment]
Thank you :)

**Comment by rossriley** [comment]
Had to make a few minor adjustments to get all the tests to pass.

Internal nested functions didn't work as a callable so I've altered to assign the function to variable. 

Nice work though, that's added a lot of extra functionality.

**Comment by bouiboui** [comment]
I see, sorry I rushed it a bit :)
That's a great project, writing code feels much more natural this way.
I'll contribute again if I can!

**Pull request merged**
