### PR TITLE
added toFixed and stubbed toPrecision, added test coverage.

### PR DESCRIPTION
**Pull request by eborden**
I'm not sure about toPrecision. It is a helpful method when you need a numeric value to fit into a specified character width for the presentation layer, but exponential returns are hairy in PHP since there is no native exponent representation.

### CODE REVIEW

**Comment by rossriley** [comment]
Though i get a failure on this test:

```
$this->assertEquals($f->toPrecision(5), "5.1235");
```

**Comment by eborden** [comment]
Yeah, toPrecision is currently stubbed with proposed functionality speced in tests. It has yet to be implemented because results for something like `1234.23->toPrecision(2)` are questionable.

**Comment by rossriley** [comment]
Sorry, didn't read the code.

Am I interpreting the goal correctly in that we are looking for it to return the equivalent of:
    sprintf( "%0.0(n)f", 123.45645678);

Where n is the value passed to precision?
So
    $n = 123.45678;
    $n->toPrecision(0);  // sprintf( "%0.00f", 123.45645678) Outputs 123
    $n->toPrecision(1);  // sprintf( "%0.01f", 123.45645678) Outputs 123.5
    $n->toPrecision(2);  // sprintf( "%0.02f", 123.45645678) Outputs 123.46
    $n->toPrecision(3);  // sprintf( "%0.03f", 123.45645678) Outputs 123.457
    $n->toPrecision(10);  // sprintf( "%0.010f", 123.45645678) Outputs 123.4567800000

**Comment by eborden** [comment]
Your examples represent toFixed or the number's "scale". Precision refers to the significant digits that represent the number in total.

``` php
$n = 123.45678;
$n->toPrecision(0); // RangeException
$n->toPrecision(1); // 1E2
$n->toPrecision(2); // 12E1
$n->toPrecision(3); // 123
$n->toPrecision(10); // 123.4567800
```

In general behavior becomes hairy when you attempt to generate precision in low numbers, thus the scientific notation (1E3 = 1000).

**Pull request merged**
